export const Periodjson = [
    { status: false, name: "Select", value: "", hide: false },
    { status: false, name: "Period 1", value: "Period 1", hide: true },
    { status: false, name: "Period 2", value: "Period 2", hide: true },
    { status: false, name: "Period 3", value: "Period 3", hide: true },
    { status: false, name: "Period 4", value: "Period 4", hide: true },
    { status: false, name: "Period 5", value: "Period 5", hide: true },
    { status: false, name: "Period 6", value: "Period 6", hide: true },
    { status: false, name: "Period 7", value: "Period 7", hide: true },
    { status: false, name: "Period 8", value: "Period 8", hide: true },
    { status: false, name: "Period 9", value: "Period 9", hide: true },
    { status: false, name: "Period 10", value: "Period 10", hide: true },
    { status: false, name: "Period 11", value: "Period 11", hide: true },
    { status: false, name: "Period 12", value: "Period 12", hide: true },
    { status: false, name: "Period I", value: "Period I", hide: false },
    { status: false, name: "Period II", value: "Period II", hide: false },
    { status: false, name: "Period III", value: "Period III", hide: false },
    { status: false, name: "Period IV", value: "Period IV", hide: false },
    { status: false, name: "Period V", value: "Period V", hide: false },
    { status: false, name: "Period VI", value: "Period VI", hide: false },
    { status: false, name: "Period VII", value: "Period VII", hide: false },
    { status: false, name: "Period VIII", value: "Period VIII", hide: false },
    { status: false, name: "Period IX", value: "Period IX", hide: false },
    { status: false, name: "Period X", value: "Period X", hide: false },
    { status: false, name: "Period XI", value: "Period XI", hide: false },
    { status: false, name: "Period XII", value: "Period XII", hide: false },
    { status: false, name: "lunch break", value: "lunch break", hide: false },
]

