   import './globals.css'
 
//  import './calendar.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Authprovider from './components/shared/utils/authprovider'
// import { getServerSession } from 'next-auth'
// import { authOptions } from './api/auth/[...nextauth]/options'
// import { redirect } from 'next/navigation'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='light'>
    {/* <body className={inter.className}>{children}</body> */}
    {/* <script defer src="https://cdn.jsdelivr.net/npm/alpinejs@3.x.x/dist/cdn.min.js"></script> */}

      <Authprovider> 
      <body className="c-bg-light c-text-light">{children}</body> 
      </Authprovider>
    </html>
  )
}


